const documents=[{id:"address",title:"Address Procedures",category:"Treasurer · Accounting Procedures",description:"Confidence levels and procedures for documenting, validating, and updating owner and parcel mailing addresses in QuickBooks.",pdf:"./documents/address-procedures.pdf",odt:"./source/Address_Procedures.odt"},{id:"secretary-checks",title:"Check Payment Processing — Secretary",category:"Secretary · Accounting Procedures",description:"Procedures for receiving payments, organizing separate deposits, preparing deposit packets, making bank deposits, and transferring packets to the Treasurer.",pdf:"./documents/check-processing-secretary.pdf",odt:"./source/Check_Payment_Processing_Secretary.odt"},{id:"treasurer-checks",title:"Check Payment Processing — Treasurer",category:"Treasurer · Accounting Procedures",description:"Procedures for receiving deposit packets, posting payments in the air-gapped QuickBooks system, reconciling deposits, printing summaries, and filing packets.",pdf:"./documents/check-processing-treasurer.pdf",odt:"./source/Check_Payment_Processing_Treasurer.odt"},{id:"directors",title:"Current Directors and Officers",category:"Board & Governance",description:"The supplied leadership roster of River Springs Ranch POA directors, corporate officers, authorized signers, and reporting contacts.",pdf:"./documents/directors-officers.pdf",odt:"./source/Directors%20and%20Officers.odt"},{id:"leadership-changes",title:"Changing and Reporting Directors and Officers",category:"Secretary · Board & Governance",description:"Internal documentation and Arizona Corporation Commission reporting steps when directors or officers are elected, appointed, removed, or replaced.",pdf:"./documents/changing-directors-officers.pdf",odt:"./source/Changing%20and%20Reporting%20Directors%20and%20Officers.odt"},{id:"roles",title:"Roles and Responsibilities",category:"Board & Governance",description:"The association’s working list of responsibilities for officers, directors, appointed positions, election staff, and hired road-maintenance staff.",pdf:"./documents/roles-responsibilities.pdf",odt:"./source/Roles%20Responsibilities.odt"},{id:"surety",title:"CNA Surety Bond",category:"Secretary · Insurance & Protection",description:"An overview of the POA’s fidelity and crime bond, examples of covered loss, items generally not covered, and annual administration responsibilities.",pdf:"./documents/surety-bond.pdf",odt:"./source/Surety%20Bond.odt"}];
const views=document.querySelectorAll("[data-view-panel]"),navButtons=document.querySelectorAll(".nav-link[data-view]"),allViewButtons=document.querySelectorAll("[data-view]"),sidebar=document.getElementById("sidebar"),menuButton=document.getElementById("mobile-menu-button"),overlay=document.getElementById("sidebar-overlay"),searchInput=document.getElementById("menu-search"),clearSearchButton=document.getElementById("clear-search"),noResults=document.getElementById("no-results"),themeButton=document.getElementById("theme-button"),mainContent=document.getElementById("main-content");
function closeMobileMenu(){sidebar.classList.remove("open");overlay.classList.remove("show");menuButton.setAttribute("aria-expanded","false")}
function setActiveNavigation(viewName){navButtons.forEach(button=>button.classList.toggle("active",button.dataset.view===viewName))}
function showView(viewName,updateHash=true){const record=documents.find(item=>item.id===viewName);if(record){populateDocumentView(record);viewName="document"}views.forEach(view=>view.classList.toggle("active",view.dataset.viewPanel===viewName));setActiveNavigation(record?record.id:viewName);if(updateHash){history.replaceState(null,"",`#${record?record.id:viewName}`)}mainContent.scrollTop=0;mainContent.focus({preventScroll:true});if(window.innerWidth<=760)closeMobileMenu()}
function populateDocumentView(record){document.getElementById("document-breadcrumb").textContent=record.title;document.getElementById("document-category").textContent=record.category;document.getElementById("document-title").textContent=record.title;document.getElementById("document-description").textContent=record.description;document.getElementById("open-pdf").href=record.pdf;const odt=document.getElementById("download-odt");odt.href=record.odt;odt.setAttribute("download","");const frame=document.getElementById("pdf-frame");frame.src=`${record.pdf}#view=FitH`;frame.title=`${record.title} PDF preview`}
function buildDocumentLibrary(){const grid=document.getElementById("document-grid");grid.innerHTML=documents.map(item=>`<article class="document-card"><span class="category">${item.category}</span><h2>${item.title}</h2><p>${item.description}</p><div class="document-card-actions"><button class="open-detail" type="button" data-open-document="${item.id}">View Details</button><a class="open-file" href="${item.pdf}" target="_blank" rel="noopener">Open PDF</a><a class="open-file" href="${item.odt}" download>Download ODT</a></div></article>`).join("");grid.querySelectorAll("[data-open-document]").forEach(button=>button.addEventListener("click",()=>showView(button.dataset.openDocument)))}
allViewButtons.forEach(button=>button.addEventListener("click",()=>{if(button.dataset.view)showView(button.dataset.view)}));
document.querySelectorAll(".nav-group-heading").forEach(button=>button.addEventListener("click",()=>{const group=button.closest(".nav-group"),collapsed=group.classList.toggle("collapsed");button.setAttribute("aria-expanded",String(!collapsed));button.querySelector(".expand-symbol").textContent=collapsed?"+":"−"}));
menuButton.addEventListener("click",()=>{const open=sidebar.classList.toggle("open");overlay.classList.toggle("show",open);menuButton.setAttribute("aria-expanded",String(open))});overlay.addEventListener("click",closeMobileMenu);
function filterNavigation(){const term=searchInput.value.trim().toLowerCase();let count=0;document.querySelectorAll(".nav-group").forEach(group=>{const links=group.querySelectorAll(".nav-link");let groupMatches=0;links.forEach(link=>{const text=`${link.textContent} ${link.dataset.search||""}`.toLowerCase(),match=!term||text.includes(term);link.hidden=!match;if(match)groupMatches++});group.hidden=Boolean(term)&&groupMatches===0;if(term&&groupMatches>0){group.classList.remove("collapsed");const heading=group.querySelector(".nav-group-heading");heading.setAttribute("aria-expanded","true");heading.querySelector(".expand-symbol").textContent="−"}count+=groupMatches});noResults.hidden=count!==0}
searchInput.addEventListener("input",filterNavigation);clearSearchButton.addEventListener("click",()=>{searchInput.value="";filterNavigation();searchInput.focus()});
themeButton.addEventListener("click",()=>{const current=document.documentElement.dataset.theme==="dark"?"dark":"light",next=current==="dark"?"light":"dark";document.documentElement.dataset.theme=next;try{localStorage.setItem("rsr-theme",next)}catch(error){}});
document.getElementById("print-page").addEventListener("click",()=>window.print());window.addEventListener("hashchange",()=>{const requested=location.hash.slice(1);if(requested)showView(requested,false)});
buildDocumentLibrary();const initial=location.hash.slice(1)||"home",valid=["home","library","guide"].includes(initial)||documents.some(item=>item.id===initial);showView(valid?initial:"home",false);
